name: nixtlaEnv
channels:
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - _python_abi3_support=1.0=hd8ed1ab_2
  - adagio=0.2.6=pyhd8ed1ab_1
  - aiohappyeyeballs=2.6.1=pyhd8ed1ab_0
  - aiohttp-cors=0.8.1=pyhd8ed1ab_0
  - alembic=1.15.2=pyhd8ed1ab_0
  - annotated-types=0.7.0=pyhd8ed1ab_1
  - anyio=4.12.0=pyhcf101f3_0
  - appdirs=1.4.4=pyhd8ed1ab_1
  - argon2-cffi=25.1.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=25.1.0=py312h4c3975b_2
  - arrow=1.4.0=pyhcf101f3_0
  - asttokens=3.0.1=pyhd8ed1ab_0
  - async-lru=2.0.5=pyh29332c3_0
  - aws-c-auth=0.8.6=hd08a7f5_4
  - aws-c-cal=0.8.7=h043a21b_0
  - aws-c-common=0.12.0=hb9d3cd8_0
  - aws-c-compression=0.3.1=h3870646_2
  - aws-c-event-stream=0.5.4=h04a3f94_2
  - aws-c-http=0.9.4=hb9b18c6_4
  - aws-c-io=0.17.0=h3dad3f2_6
  - aws-c-mqtt=0.12.2=h108da3e_2
  - aws-c-s3=0.7.13=h822ba82_2
  - aws-c-sdkutils=0.2.3=h3870646_2
  - aws-checksums=0.2.3=h3870646_2
  - aws-crt-cpp=0.31.0=h55f77e1_4
  - aws-sdk-cpp=1.11.510=h37a5c72_3
  - azure-core-cpp=1.14.0=h5cfcd09_0
  - azure-identity-cpp=1.10.0=h113e628_0
  - azure-storage-blobs-cpp=12.13.0=h3cf044e_1
  - azure-storage-common-cpp=12.8.0=h736e048_1
  - azure-storage-files-datalake-cpp=12.12.0=ha633028_1
  - babel=2.17.0=pyhd8ed1ab_0
  - backports.zstd=1.3.0=py312h90b7ffd_0
  - beautifulsoup4=4.14.3=pyha770c72_0
  - black=25.12.0=pyh866005b_0
  - bleach=6.3.0=pyhcf101f3_0
  - bleach-with-css=6.3.0=h5f6438b_0
  - brotli=1.1.0=hb9d3cd8_2
  - brotli-bin=1.1.0=hb9d3cd8_2
  - brotli-python=1.2.0=py312h3dd09e2_0
  - bzip2=1.0.8=h4bc722e_7
  - c-ares=1.34.4=hb9d3cd8_0
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cachetools=6.2.4=pyhd8ed1ab_0
  - cffi=2.0.0=py312h35888ee_0
  - click=8.3.1=pyh8f84b5b_1
  - cloudpickle=3.1.1=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - colorful=0.5.8=pyhd8ed1ab_0
  - colorlog=6.9.0=pyh707e725_1
  - comm=0.2.3=pyhe01879c_0
  - contourpy=1.3.1=py312h68727a3_0
  - coreforecast=0.0.16=py312h68727a3_0
  - cpython=3.12.12=py312hd8ed1ab_1
  - cryptography=46.0.3=py312ha4b625e_1
  - cycler=0.12.1=pyhd8ed1ab_1
  - debugpy=1.8.19=py312h372c3de_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - distlib=0.4.0=pyhd8ed1ab_0
  - exceptiongroup=1.3.1=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - filelock=3.20.2=pyhd8ed1ab_0
  - fonttools=4.57.0=py312h178313f_0
  - fqdn=1.5.1=pyhd8ed1ab_1
  - freetype=2.13.3=h48d6fc4_0
  - fs=2.4.16=pyhd8ed1ab_0
  - fsspec=2025.3.2=pyhd8ed1ab_0
  - fugue=0.9.1=pyhd8ed1ab_1
  - gflags=2.2.2=h5888daf_1005
  - glog=0.7.1=hbabe93e_0
  - gmp=6.3.0=hac33072_2
  - gmpy2=2.2.1=py312hcaba1f9_2
  - google-api-core=2.28.1=pyhd8ed1ab_0
  - google-auth=2.45.0=pyhd8ed1ab_0
  - googleapis-common-protos=1.72.0=pyhd8ed1ab_0
  - greenlet=3.1.1=py312h2ec8cdc_1
  - grpcio=1.67.1=py312hacea422_2
  - h11=0.16.0=pyhd8ed1ab_0
  - h2=4.3.0=pyhcf101f3_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - httpcore=1.0.9=pyh29332c3_0
  - httpx=0.28.1=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=he02047a_0
  - importlib-metadata=8.6.1=pyha770c72_0
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - ipykernel=7.1.0=pyha191276_0
  - ipython=9.9.0=pyh53cf698_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - ipywidgets=8.1.8=pyhd8ed1ab_0
  - isoduration=20.11.0=pyhd8ed1ab_1
  - isort=7.0.0=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhcf101f3_1
  - joblib=1.4.2=pyhd8ed1ab_1
  - json5=0.13.0=pyhd8ed1ab_0
  - jsonpointer=3.0.0=pyhcf101f3_3
  - jsonschema=4.25.1=pyhe01879c_0
  - jsonschema-specifications=2025.9.1=pyhcf101f3_0
  - jsonschema-with-format-nongpl=4.25.1=he01879c_0
  - jupyter=1.1.1=pyhd8ed1ab_1
  - jupyter-lsp=2.3.0=pyhcf101f3_0
  - jupyter_client=8.7.0=pyhcf101f3_0
  - jupyter_console=6.6.3=pyhd8ed1ab_1
  - jupyter_core=5.9.1=pyhc90fa1f_0
  - jupyter_events=0.12.0=pyh29332c3_0
  - jupyter_server=2.17.0=pyhcf101f3_0
  - jupyter_server_terminals=0.5.3=pyhd8ed1ab_1
  - jupyterlab=4.5.1=pyhd8ed1ab_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_2
  - jupyterlab_server=2.28.0=pyhcf101f3_0
  - jupyterlab_widgets=3.0.16=pyhcf101f3_1
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.8=py312h84d6215_0
  - krb5=1.21.3=h659f571_0
  - lark=1.3.1=pyhd8ed1ab_0
  - lcms2=2.17=h717163a_0
  - ld_impl_linux-64=2.43=h712a8e2_4
  - lerc=4.0.0=h27087fc_0
  - libabseil=20240722.0=cxx17_hbbce691_4
  - libarrow=19.0.1=h1938f28_3_cuda
  - libarrow-acero=19.0.1=hb826db4_3_cuda
  - libarrow-dataset=19.0.1=hb826db4_3_cuda
  - libarrow-substrait=19.0.1=hbf482d9_3_cuda
  - libblas=3.9.0=31_h59b9bed_openblas
  - libbrotlicommon=1.1.0=hb9d3cd8_2
  - libbrotlidec=1.1.0=hb9d3cd8_2
  - libbrotlienc=1.1.0=hb9d3cd8_2
  - libcblas=3.9.0=31_he106b2a_openblas
  - libcrc32c=1.1.2=h9c3ff4c_0
  - libcurl=8.13.0=h332b0f4_0
  - libdeflate=1.23=h4ddbbb0_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libev=4.33=hd590300_2
  - libevent=2.1.12=hf998b51_1
  - libexpat=2.7.0=h5888daf_0
  - libffi=3.4.6=h2dba641_1
  - libgcc=14.2.0=h767d61c_2
  - libgcc-ng=14.2.0=h69a702a_2
  - libgfortran=14.2.0=h69a702a_2
  - libgfortran5=14.2.0=hf1ad2bd_2
  - libgomp=14.2.0=h767d61c_2
  - libgoogle-cloud=2.36.0=h2b5623c_0
  - libgoogle-cloud-storage=2.36.0=h0121fbd_0
  - libgrpc=1.67.1=h25350d4_2
  - libiconv=1.18=h4ce23a2_1
  - libjpeg-turbo=3.0.0=hd590300_1
  - liblapack=3.9.0=31_h7ac8fdf_openblas
  - liblzma=5.8.1=hb9d3cd8_0
  - libnghttp2=1.64.0=h161d5f1_0
  - libnsl=2.0.1=hd590300_0
  - libopenblas=0.3.29=pthreads_h94d23a6_0
  - libopentelemetry-cpp=1.18.0=hfcad708_1
  - libopentelemetry-cpp-headers=1.18.0=ha770c72_1
  - libparquet=19.0.1=h3f30f2e_3_cuda
  - libpng=1.6.47=h943b412_0
  - libprotobuf=5.28.3=h6128344_1
  - libre2-11=2024.07.02=hbbce691_2
  - libsodium=1.0.20=h4ab18f5_0
  - libsqlite=3.49.1=hee588c1_2
  - libssh2=1.11.1=hf672d98_0
  - libstdcxx=14.2.0=h8f9b012_2
  - libstdcxx-ng=14.2.0=h4852527_2
  - libthrift=0.21.0=h0e7cc3e_0
  - libtiff=4.7.0=hd9ff511_3
  - libtorch=2.6.0=cpu_generic_haed06de_0
  - libunwind=1.8.3=h65a8314_0
  - libutf8proc=2.10.0=h4c51ac1_0
  - libuuid=2.38.1=h0b41bf4_0
  - libuv=1.51.0=hb03c661_1
  - libwebp-base=1.5.0=h851e524_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.14.0=h8d12d68_1
  - libzlib=1.3.1=hb9d3cd8_2
  - lightning-utilities=0.15.2=pyhd8ed1ab_0
  - llvmlite=0.44.0=py312h374181b_1
  - lz4-c=1.10.0=h5888daf_1
  - mako=1.3.9=pyhd8ed1ab_0
  - markupsafe=3.0.2=py312h178313f_1
  - matplotlib-base=3.10.1=py312hd3ec401_0
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - mistune=3.2.0=pyhcf101f3_0
  - mizani=0.14.3=pyhd8ed1ab_0
  - mlforecast=1.0.2=pyhd8ed1ab_0
  - mpc=1.3.1=h24ddda3_1
  - mpfr=4.2.1=h90cbb55_3
  - mpmath=1.3.0=pyhd8ed1ab_1
  - msgpack-python=1.1.2=py312hd9148b4_1
  - munkres=1.1.4=pyh9f0ad1d_0
  - mypy_extensions=1.1.0=pyha770c72_0
  - nbclient=0.10.4=pyhd8ed1ab_0
  - nbconvert-core=7.16.6=pyhcf101f3_1
  - nbformat=5.10.4=pyhd8ed1ab_1
  - ncurses=6.5=h2d0b736_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - networkx=3.6.1=pyhcf101f3_0
  - neuralforecast=3.1.2=pyhd8ed1ab_0
  - nlohmann_json=3.11.3=he02047a_1
  - nomkl=1.0=h5ca1d4c_0
  - notebook=7.5.1=pyhcf101f3_0
  - notebook-shim=0.2.4=pyhd8ed1ab_1
  - numba=0.61.0=py312h2e6246c_1
  - numpy=2.1.3=py312h58c1407_0
  - opencensus=0.11.3=pyhd8ed1ab_1
  - opencensus-context=0.1.3=py312h7900ff3_4
  - openjpeg=2.5.3=h5fbd93e_0
  - openssl=3.6.0=h26f9b46_0
  - optree=0.18.0=py312hd9148b4_0
  - optuna=4.2.1=pyhd8ed1ab_0
  - orc=2.1.1=h2271f48_0
  - overrides=7.7.0=pyhd8ed1ab_1
  - packaging=24.2=pyhd8ed1ab_2
  - pandas=2.2.3=py312hf9745cd_1
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.5=pyhcf101f3_0
  - pathspec=0.12.1=pyhd8ed1ab_1
  - patsy=1.0.1=pyhd8ed1ab_1
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pillow=11.1.0=py312h80c1187_0
  - pip=25.0.1=pyh8b19718_0
  - platformdirs=4.5.1=pyhcf101f3_0
  - plotnine=0.15.2=pyhd8ed1ab_0
  - prometheus-cpp=1.3.0=ha5d0236_0
  - prometheus_client=0.23.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - prompt_toolkit=3.0.52=hd8ed1ab_0
  - propcache=0.3.1=py312h178313f_0
  - proto-plus=1.27.0=pyhd8ed1ab_0
  - protobuf=5.28.3=py312h2ec8cdc_0
  - psutil=7.2.1=py312h5253ce2_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - py-spy=0.4.1=he182f42_0
  - pyarrow=19.0.1=py312h7900ff3_0
  - pyarrow-core=19.0.1=py312h09cf70e_0_cuda
  - pyasn1=0.6.1=pyhd8ed1ab_2
  - pyasn1-modules=0.4.2=pyhd8ed1ab_0
  - pybind11=3.0.1=pyh7a1b43c_0
  - pybind11-global=3.0.1=pyhc7ab6ef_0
  - pycparser=2.22=pyh29332c3_1
  - pydantic=2.11.10=pyh3cfb1c2_0
  - pydantic-core=2.33.2=py312h680f630_0
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyopenssl=25.3.0=pyhd8ed1ab_0
  - pyparsing=3.2.3=pyhd8ed1ab_1
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.12.9=h9e4cc4f_1_cpython
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - python-fastjsonschema=2.21.2=pyhe01879c_0
  - python-gil=3.12.12=hd8ed1ab_1
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.12=6_cp312
  - pytokens=0.3.0=pyhcf101f3_0
  - pytorch=2.6.0=cpu_generic_py312_h1c73833_0
  - pytorch-lightning=2.6.0=pyhcf101f3_0
  - pytz=2024.1=pyhd8ed1ab_0
  - pyu2f=0.1.5=pyhd8ed1ab_1
  - pyyaml=6.0.2=py312h178313f_2
  - pyzmq=27.1.0=py312hfb55c3c_0
  - qhull=2020.2=h434a139_5
  - ray-core=2.44.1=py312h1d27fe0_0
  - ray-default=2.44.1=py312hd4369dc_0
  - ray-tune=2.44.1=py312h7900ff3_0
  - re2=2024.07.02=h9925aae_2
  - readline=8.2=h8c095d6_2
  - referencing=0.37.0=pyhcf101f3_0
  - rfc3339-validator=0.1.4=pyhd8ed1ab_1
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rfc3987-syntax=1.1.0=pyhe01879c_1
  - rpds-py=0.30.0=py312h868fb18_0
  - rsa=4.9.1=pyhd8ed1ab_0
  - s2n=1.5.14=h6c98b2b_0
  - scikit-learn=1.6.1=py312h7a48858_0
  - scipy=1.15.2=py312ha707e6e_0
  - send2trash=2.0.0=pyha191276_0
  - setproctitle=1.3.7=py312h5253ce2_0
  - setuptools=78.1.0=pyhff2d567_0
  - six=1.17.0=pyhd8ed1ab_0
  - sleef=3.9.0=ha0421bc_0
  - smart_open=7.5.0=pyhcf101f3_0
  - snappy=1.2.1=h8bd8927_1
  - sniffio=1.3.1=pyhd8ed1ab_2
  - soupsieve=2.8.1=pyhd8ed1ab_0
  - sqlalchemy=2.0.40=py312h66e93f0_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - statsforecast=2.0.1=py312h68727a3_0
  - statsmodels=0.14.6=py312h4f23490_0
  - sympy=1.14.0=pyh2585a3b_105
  - tensorboardx=2.6.2.2=pyhd8ed1ab_1
  - terminado=0.18.1=pyhc90fa1f_1
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tinycss2=1.5.1=pyhcf101f3_0
  - tk=8.6.13=noxft_h4845f30_101
  - tomli=2.3.0=pyhcf101f3_0
  - torchmetrics=1.8.2=pyhd8ed1ab_0
  - tornado=6.5.4=py312h961da02_0
  - tqdm=4.67.1=pyhd8ed1ab_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - triad=0.9.8=pyhd8ed1ab_1
  - typing-extensions=4.13.1=hf5ce1d7_0
  - typing-inspection=0.4.2=pyhd8ed1ab_1
  - typing_extensions=4.13.1=pyh29332c3_0
  - typing_utils=0.1.0=pyhd8ed1ab_1
  - tzdata=2025b=h78e105d_0
  - unicodedata2=16.0.0=py312h66e93f0_0
  - uri-template=1.3.0=pyhd8ed1ab_1
  - utilsforecast=0.2.12=pyhd8ed1ab_0
  - virtualenv=20.33.1=pyhd8ed1ab_0
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - webcolors=25.10.0=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_3
  - websocket-client=1.9.0=pyhd8ed1ab_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - widgetsnbextension=4.0.15=pyhd8ed1ab_0
  - wrapt=2.0.1=py312h4c3975b_1
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - yaml=0.2.5=h7f98852_2
  - zeromq=4.3.5=h387f397_9
  - zipp=3.21.0=pyhd8ed1ab_1
  - zlib=1.3.1=hb9d3cd8_2
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
      - aiohttp==3.11.16
      - aiosignal==1.3.2
      - attrs==25.3.0
      - certifi==2025.1.31
      - charset-normalizer==3.4.1
      - datasetsforecast==1.0.0
      - frozenlist==1.5.0
      - idna==3.10
      - multidict==6.3.2
      - requests==2.32.3
      - urllib3==2.3.0
      - xlrd==2.0.1
      - yarl==1.19.0
prefix: /home/ixi_eulogy_ixi/anaconda3/envs/nixtlaEnv
